import os, textwrap, sys
import subprocess
from pathlib import Path

def c(s):
    print(">", s)
    subprocess.check_call(s, shell=True)


ROOT = Path(__name__).absolute().parent.parent.parent.parent
print(ROOT)

c("dotnet publish")

os.chdir("bin/Debug/publish")

collected = os.popen("dllyaml --files . --redirects").read()

file_cont = """<?xml version="1.0" encoding="utf-8"?>
<!-- this file generated by generate_binding_redirects.py and dllyaml -->
<configuration>
<runtime>
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
%s
</assemblyBinding>
</runtime>
</configuration>
""" % collected

c(".\\BindingRedirects.exe")

targets = [
    "./BindingRedirects.exe.config",
    Path(sys.base_prefix) / "python.exe.config"
]

for t in targets:
    print("Writing app config to to:", t)
    open(t, "w").write(file_cont)

